name: Sync to Local Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout External Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Para obtener todo el historial

      - name: Sync Changes to Local Repository
        run: |
          git remote add local https://${{ secrets.MIRROR_TOKEN }}@github.com/luis-ar/ContigoVoy.git
          git push local main
