name: Mirror to Local Repo (Copy)

on:
  push:
    branches:
      - main # Activa el workflow cuando hay un push en la rama main del repositorio externo

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout original repo (ContigoVoy2)
        uses: actions/checkout@v2
        with:
          repository: NEONHOUSELED-SAC/ContigoVoy2 # Repositorio externo
          fetch-depth: 0 # Obtiene todo el historial de Git

      - name: Set up Git
        run: |
          git config --global user.email "luisdemaryori@gmail.com"
          git config --global user.name "luis-ar"
          echo "https://github.com:${{ secrets.MIRROR_TOKEN }}@github.com" > ~/.git-credentials

      - name: Push to local repo (copy)
        run: |
          git remote add copy https://github.com:${{ secrets.MIRROR_TOKEN }}@github.com/luis-ar/ContigoVoy.git
          git push copy main
