name: Sync to Mirror

on:
  push:
    branches:
      - main 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to Mirror
        env:
          MIRROR: ${{ secrets.MIRROR }}
        run: |
          git remote add mirror https://$MIRROR@github.com/luis-ar/ContigoVoy.git
          git push --mirror mirror
